version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"